name = "araoye-portfolio"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
cwd = "."

[build.upload]
format = "service-worker"

[[build.upload.rules]]
type = "ESModule"
globs = ["**/*.js"]

[[build.upload.rules]]
type = "CommonJS"
globs = ["**/*.js"]

[[build.upload.rules]]
type = "CompiledWasm"
globs = ["**/*.wasm"]

[[build.upload.rules]]
type = "Text"
globs = ["**/*.txt", "**/*.html", "**/*.css", "**/*.json"]

[[build.upload.rules]]
type = "Data"
globs = ["**/*.bin", "**/*.dat"]

[[build.upload.rules]]
type = "HTTPHeader"
globs = ["**/*.html"]
headers = { "Cache-Control" = "public, max-age=0, must-revalidate" }
